version: 0.2

phases:
  install:
    commands:
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
  build:
    commands:
      - IMAGE_TAG=$(date +%Y%m%d-%H%M)
      - echo "Build image"
      - docker build -t ${REPOSITORY_URI}:${IMAGE_TAG} -f Dockerfile .
  post_build:
    commands:
      - echo "Push image"
      - docker push ${REPOSITORY_URI}:${IMAGE_TAG}
      - printf '[{"name":"%s","imageUri":"%s"}]' ${CONTAINER_NAME} ${REPOSITORY_URI}:${IMAGE_TAG} > imagedefinitions.json

artifacts:
  files: imagedefinitions.json


